services:
  node-app:
    container_name: node_app_demo
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/home/server
      - /home/server/node_modules
    depends_on:
      - mongodb  
    networks:
      - mern_stack_yatify_network
  
  mongodb:
    container_name: mongoDB
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern_stack_yatify_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-browser:
    image: mongo-express
    container_name: Browser_mongo_console
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - mern_stack_yatify_network

  client-app:
    container_name: client-app-demo
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/home/client
      - /home/client/node_modules
    depends_on:
      - node-app
    networks:
      - mern_stack_yatify_network
    
networks:
   mern_stack_yatify_network:
    driver: bridge

volumes:
   mongodb_data:
    driver: local
